development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development_db
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test_db
  pool: 5
  username: myapp
  password: password1