default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  port: 5432
  username: myapp
  password: password1
test:
  <<: *default
  database: myapp_test
  port: 5432
  username: myapp
  password: password1

production:
  <<: *default
  url: <%= ENV['MY_APP_DATABASE_URL'] %>